; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Cheat Engine 5.4
AppVerName=Cheat Engine 5.4
AppPublisher=Dark Byte
AppPublisherURL=http://www.cheatengine.org/
AppSupportURL=http://www.cheatengine.org/
AppUpdatesURL=http://www.cheatengine.org/
DefaultDirName={pf}\Cheat Engine
DefaultGroupName=Cheat Engine 5.4
AllowNoIcons=yes
LicenseFile=..\Release\License.txt
InfoAfterFile=..\Release\readme.txt
OutputBaseFilename=CheatEngine54

[InstallDelete]
Type: files; Name: "{app}\kerneldata.dat"
Type: files; Name: "{app}\CEProtect.dat"



[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"

[code]
procedure UninstallDriver();
var
  ResultCode: Integer;
begin
  Exec(ExpandConstant('{app}Kernelmoduleunloader.exe'),'/SETUP',ExpandConstant('{app}'),0,ewWaitUntilTerminated,ResultCode);
  //try to delete the dbk32.sys file if there is one there
  
  DeleteFile(ExpandConstant('{app}dbk32.sys'));
  DeleteFile(ExpandConstant('{app}dbk32.bak'));

  RenameFile(ExpandConstant('{app}dbk32.sys'),ExpandConstant('{app}dbk32.bak'));
  
end;

function NeedRestart(): Boolean;
var restart: boolean;
    ResultDWord: Cardinal;
begin
  restart:=false;

  if not RegQueryDWordValue(HKCU,'Software\Cheat Engine','First time User',ResultDWord) then
    RegWriteDWordValue(HKEY_CURRENT_USER,  'Software\Cheat Engine', 'First Time User',1);
  
  if RegQueryDWordValue(HKCU,'Software\Cheat Engine','Use Processwatcher',ResultDWord) then
    if ResultDWord<>0 then restart:=true;

  if RegQueryDWordValue(HKCU,'Software\Cheat Engine','Use Kernel Debugger',ResultDWord) then
    if ResultDWord<>0 then restart:=true;
    
  //disable all kernel crap

  RegWriteDWordValue(HKEY_CURRENT_USER,  'Software\Cheat Engine', 'StealthOnExecute',0);
  RegWriteDWordValue(HKEY_CURRENT_USER,  'Software\Cheat Engine', 'Protect CE',0);
  RegWriteDWordValue(HKEY_CURRENT_USER,  'Software\Cheat Engine', 'Undo memory changes:Force writable',0);
  RegWriteDWordValue(HKEY_CURRENT_USER,  'Software\Cheat Engine', 'Undo memory changes',0);
  RegWriteDWordValue(HKEY_CURRENT_USER,  'Software\Cheat Engine', 'Use Kernel Debugger',0);
  RegWriteDWordValue(HKEY_CURRENT_USER,  'Software\Cheat Engine', 'Use Processwatcher',0);
  
  RegWriteDWordValue(HKEY_CURRENT_USER,  'Software\Cheat Engine', 'Use Hyperscan if posible',0);
  

  result:=restart;
end;


//uninstall

function InitializeUninstall(): Boolean;
begin
  //run the unloader
  UninstallDriver();
  result:=true;
end;

function UninstallNeedRestart(): Boolean;
var ResultDWord: Cardinal;
begin
  result:=false;
  //check the registry
  //if the kernel debugger is enabled, or the processwatcher enabled then return true
  UninstallDriver(); //second time removes the link if the first time failed
  
  if RegQueryDWordValue(HKCU,'Software\Cheat Engine','Use Processwatcher',ResultDWord) then
    if ResultDWord<>0 then result:=true;
    
  if RegQueryDWordValue(HKCU,'Software\Cheat Engine','Use Kernel Debugger',ResultDWord) then
    if ResultDWord<>0 then result:=true;


  //delete the reg
  RegDeleteKeyIncludingSubkeys(HKEY_CURRENT_USER,'Software\Cheat Engine');

end;

[Dirs]
;go ahead, scream like a pig about this one, I know you want to
Name: "{app}"; permissions: everyone-modify;


[Files]
Source: "..\cheatengine.exe"; DestDir: "{app}"; DestName: "Cheat Engine.exe"; Flags: ignoreversion
Source: "..\CEHook.dll"; DestDir: "{app}"; DestName: "CEHook.dll"; Flags: ignoreversion

Source: "..\LockedString.bmp"; DestDir: "{app}"; DestName: "LockedString.bmp"; Flags: ignoreversion
Source: "..\UnLockedString.bmp"; DestDir: "{app}"; DestName: "UnLockedString.bmp"; Flags: ignoreversion
Source: "..\TextureString.bmp"; DestDir: "{app}"; DestName: "TextureString.bmp"; Flags: ignoreversion
Source: "..\targettexture.bmp"; DestDir: "{app}"; DestName: "targettexture.bmp"; Flags: ignoreversion
Source: "..\movementtexture.bmp"; DestDir: "{app}"; DestName: "movementtexture.bmp"; Flags: ignoreversion
Source: "..\Locktexture.bmp"; DestDir: "{app}"; DestName: "Locktexture.bmp"; Flags: ignoreversion
Source: "..\Black.bmp"; DestDir: "{app}"; DestName: "Black.bmp"; Flags: ignoreversion
Source: "..\dxhook.dll"; DestDir: "{app}"; DestName: "dxhook.dll"; Flags: ignoreversion
Source: "..\pscan.dll"; DestDir: "{app}"; DestName: "pscan.dll"; Flags: ignoreversion
Source: "..\directxhook\D3DX81ab.dll"; DestDir: "{sys}"; DestName: "D3DX81ab.dll";
Source: "..\directxhook\d3dx9.dll"; DestDir: "{sys}"; DestName: "d3dx9.dll";


Source: "..\Kernelmoduleunloader.exe"; DestDir: "{app}"; DestName: "Kernelmoduleunloader.exe"; Flags: ignoreversion
Source: "..\driver.dat"; DestDir: "{app}"; DestName: "driver.dat"; Flags: ignoreversion
;comment the next 2 lines for the baby version
Source: "..\dbk32.dll"; DestDir: "{app}"; DestName: "dbk32.dll"; Flags: ignoreversion
Source: "..\dbk32.sys"; DestDir: "{app}"; DestName: "dbk32.sys"; Flags: ignoreversion; BeforeInstall: UninstallDriver
Source: "..\EmptyProcess.exe"; DestDir: "{app}"; DestName: "EmptyProcess.exe"; Flags: ignoreversion
Source: "..\EmptyDLL.dll"; DestDir: "{app}"; DestName: "EmptyDLL.exe"; Flags: ignoreversion
Source: "..\Systemcallretriever.exe"; DestDir: "{app}"; DestName: "Systemcallretriever.exe"; Flags: ignoreversion
Source: "..\systemcallsignal.exe"; DestDir: "{app}"; DestName: "systemcallsignal.exe"; Flags: ignoreversion

Source: "..\stealth.dll"; DestDir: "{app}"; DestName: "stealth.dll"; Flags: ignoreversion

Source: "..\CHEAT ENGINE.HLP"; DestDir: "{app}"; DestName: "Cheat Engine.hlp"; Flags: ignoreversion
Source: "..\CHEAT ENGINE.CNT"; DestDir: "{app}"; DestName: "Cheat Engine.cnt"; Flags: ignoreversion

Source: "..\Tutorial\Project1.exe"; DestDir: "{app}"; DestName: "Tutorial.exe"; Flags: ignoreversion
Source: "..\Registry Reset\ceregreset.exe"; DestDir: "{app}"; DestName: "ceregreset.exe"; Flags: ignoreversion

;Source: "..\Cheat Engine Net\Client\client.exe"; DestDir: "{app}"; DestName: "Cheat Engine Client.exe"; Flags: ignoreversion
;Source: "..\Cheat Engine Net\Server\ceserver.exe"; DestDir: "{app}"; DestName: "Cheat Engine Server.exe"; Flags: ignoreversion
;Source: "..\Cheat Engine Client.exe"; DestDir: "{app}"; DestName: "Cheat Engine Client.exe"; Flags: ignoreversion
;Source: "..\Cheat Engine Server.exe"; DestDir: "{app}"; DestName: "Cheat Engine Server.exe"; Flags: ignoreversion


; Plugin example
Source: "..\plugin\example-c\release\example-c.dll"; DestDir: "{app}\Plugins\example-c\"; DestName: "example-c.dll"; Flags: ignoreversion
Source: "..\plugin\example-c\example-c.cpp"; DestDir: "{app}\Plugins\example-c\"; DestName: "example-c.cpp"; Flags: ignoreversion
Source: "..\plugin\example-c\example-c.def"; DestDir: "{app}\Plugins\example-c\"; DestName: "example-c.def"; Flags: ignoreversion
Source: "..\plugin\example-c\example-c.h"; DestDir: "{app}\Plugins\example-c\"; DestName: "example-c.h"; Flags: ignoreversion
Source: "..\plugin\example-c\example-c.sln"; DestDir: "{app}\Plugins\example-c\"; DestName: "example-c.sln"; Flags: ignoreversion
Source: "..\plugin\example-c\example-c.vcproj"; DestDir: "{app}\Plugins\example-c\"; DestName: "example-c.vcproj"; Flags: ignoreversion

; Delphi Plugin example
Source: "..\plugin\example\exampleplugin.dll"; DestDir: "{app}\Plugins\example-delphi\"; DestName: "exampleplugin.dll"; Flags: ignoreversion
Source: "..\plugin\example\exampleplugin.cfg"; DestDir: "{app}\Plugins\example-delphi\"; DestName: "exampleplugin.cfg"; Flags: ignoreversion
Source: "..\plugin\example\exampleplugin.dof"; DestDir: "{app}\Plugins\example-delphi\"; DestName: "exampleplugin.dof"; Flags: ignoreversion
Source: "..\plugin\example\exampleplugin.res"; DestDir: "{app}\Plugins\example-delphi\"; DestName: "exampleplugin.res"; Flags: ignoreversion
Source: "..\plugin\example\exampleplugin.dpr"; DestDir: "{app}\Plugins\example-delphi\"; DestName: "exampleplugin.dpr"; Flags: ignoreversion
Source: "..\plugin\example\Unit1.pas"; DestDir: "{app}\Plugins\example-delphi\"; DestName: "Unit1.pas"; Flags: ignoreversion

Source: "..\plugin\plugins.rtf"; DestDir: "{app}\Plugins\"; DestName: "plugins.rtf"; Flags: ignoreversion

Source: "..\include\*"; DestDir: "{app}\include\";
Source: "..\example scripts\*"; DestDir: "{app}\example scripts\";
Source: "..\ucc12.dll"; DestDir: "{app}";
Source: "..\undercdll.dll"; DestDir: "{app}";

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Cheat Engine 5.4"; Filename: "{app}\Cheat Engine.exe"
Name: "{group}\Cheat Engine tutorial"; Filename: "{app}\Tutorial.exe"
Name: "{group}\Cheat Engine help"; Filename: "{app}\Cheat Engine.hlp"
Name: "{group}\Plugin Documentation"; Filename: "{app}\Plugins\plugins.rtf"
;Name: "{group}\Network\Cheat Engine Client"; Filename: "{app}\Cheat Engine Client.exe"
;Name: "{group}\Network\Cheat Engine Server"; Filename: "{app}\Cheat Engine Server.exe"

Name: "{group}\Kernel stuff\Unload kernel module"; Filename: "{app}\Kernelmoduleunloader.exe"
Name: "{group}\Kernel stuff\Gather kernel data"; Filename: "{app}\Systemcallretriever.exe"
Name: "{group}\Reset settings"; Filename: "{app}\ceregreset.exe"

Name: "{group}\Uninstall Cheat Engine"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Cheat Engine"; Filename: "{app}\Cheat Engine.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Cheat Engine.exe"; Description: "Launch Cheat Engine 5.4"; Flags: nowait postinstall skipifsilent
