CC = gcc
LD = ld

all:
	@${CC} parsevmloadermap.c -o parsevmloadermap
	@echo "parsevmloadermap created"	
	
clean:
	@rm -f *.o
	@rm -f *.bin
	@rm -f *.map
	@rm -f parsevmloadermap
	@echo "parsevmloadermap cleaned"	
	
