object frmPatcherMaker3: TfrmPatcherMaker3
  Left = 290
  Top = 217
  BorderIcons = []
  BorderStyle = bsDialog
  Caption = 'Patcher maker'
  ClientHeight = 356
  ClientWidth = 412
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -14
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 120
  TextHeight = 16
  object Icon: TImage
    Left = 265
    Top = 89
    Width = 39
    Height = 39
  end
  object Label1: TLabel
    Left = 0
    Top = 217
    Width = 57
    Height = 16
    Caption = 'Message'
  end
  object Label2: TLabel
    Left = 266
    Top = 39
    Width = 26
    Height = 16
    Caption = 'Title'
  end
  object PatchList: TListBox
    Left = 0
    Top = 0
    Width = 260
    Height = 215
    ItemHeight = 16
    PopupMenu = PopupMenu1
    TabOrder = 0
    OnDblClick = PatchListDblClick
  end
  object Button1: TButton
    Left = 266
    Top = 4
    Width = 139
    Height = 30
    Caption = 'Add address manually'
    TabOrder = 1
    OnClick = Button1Click
  end
  object Button3: TButton
    Left = 268
    Top = 315
    Width = 139
    Height = 31
    Caption = 'Generate Trainer'
    Default = True
    TabOrder = 2
    OnClick = Button3Click
  end
  object Button2: TButton
    Left = 266
    Top = 266
    Width = 139
    Height = 31
    Cancel = True
    Caption = 'Cancel'
    TabOrder = 3
    OnClick = Button2Click
  end
  object Button4: TButton
    Left = 314
    Top = 94
    Width = 92
    Height = 30
    Caption = 'Change Icon'
    TabOrder = 4
    OnClick = Button4Click
  end
  object memoMessage: TMemo
    Left = 0
    Top = 235
    Width = 258
    Height = 121
    Lines.Strings = (
      'Default file patcher. '
      ''
      '--------------------------------------------'
      'Generated by Cheat Engine.')
    ScrollBars = ssVertical
    TabOrder = 5
  end
  object editTitle: TEdit
    Left = 266
    Top = 59
    Width = 139
    Height = 21
    TabOrder = 6
    Text = 'CE Patch Trainer'
  end
  object PopupMenu1: TPopupMenu
    OnPopup = PopupMenu1Popup
    Left = 64
    Top = 48
    object Edit1: TMenuItem
      Caption = 'Edit'
      OnClick = Edit1Click
    end
    object Remove1: TMenuItem
      Caption = 'Remove'
      OnClick = Remove1Click
    end
  end
  object OpenDialog1: TOpenDialog
    Filter = 'Icon files|*.dll;*.exe;*.ico'
    Left = 216
    Top = 104
  end
  object SaveDialog1: TSaveDialog
    DefaultExt = 'EXE'
    Filter = 'Executable files (*.exe)|*.exe'
    Options = [ofOverwritePrompt, ofHideReadOnly, ofPathMustExist, ofEnableSizing]
    Left = 248
    Top = 256
  end
end
