object frmPatcherMaker3: TfrmPatcherMaker3
  Left = 290
  Top = 217
  BorderIcons = []
  BorderStyle = bsDialog
  Caption = 'Patcher maker'
  ClientHeight = 289
  ClientWidth = 335
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Icon: TImage
    Left = 215
    Top = 72
    Width = 32
    Height = 32
  end
  object Label1: TLabel
    Left = 0
    Top = 176
    Width = 43
    Height = 13
    Caption = 'Message'
  end
  object Label2: TLabel
    Left = 216
    Top = 32
    Width = 20
    Height = 13
    Caption = 'Title'
  end
  object PatchList: TListBox
    Left = 0
    Top = 0
    Width = 211
    Height = 175
    ItemHeight = 13
    PopupMenu = PopupMenu1
    TabOrder = 0
    OnDblClick = PatchListDblClick
  end
  object Button1: TButton
    Left = 216
    Top = 3
    Width = 113
    Height = 25
    Caption = 'Add address manually'
    TabOrder = 1
    OnClick = Button1Click
  end
  object Button3: TButton
    Left = 218
    Top = 256
    Width = 113
    Height = 25
    Caption = 'Generate Trainer'
    Default = True
    TabOrder = 2
    OnClick = Button3Click
  end
  object Button2: TButton
    Left = 216
    Top = 216
    Width = 113
    Height = 25
    Cancel = True
    Caption = 'Cancel'
    TabOrder = 3
    OnClick = Button2Click
  end
  object Button4: TButton
    Left = 255
    Top = 76
    Width = 75
    Height = 25
    Caption = 'Change Icon'
    TabOrder = 4
    OnClick = Button4Click
  end
  object memoMessage: TMemo
    Left = 0
    Top = 191
    Width = 210
    Height = 98
    Lines.Strings = (
      'Default file patcher. '
      ''
      '--------------------------------------------'
      'Generated by Cheat Engine.')
    ScrollBars = ssVertical
    TabOrder = 5
  end
  object editTitle: TEdit
    Left = 216
    Top = 48
    Width = 113
    Height = 21
    TabOrder = 6
    Text = 'CE Patch Trainer'
  end
  object PopupMenu1: TPopupMenu
    OnPopup = PopupMenu1Popup
    Left = 64
    Top = 48
    object Edit1: TMenuItem
      Caption = 'Edit'
      OnClick = Edit1Click
    end
    object Remove1: TMenuItem
      Caption = 'Remove'
      OnClick = Remove1Click
    end
  end
  object OpenDialog1: TOpenDialog
    Filter = 'Icon files|*.dll;*.exe;*.ico'
    Left = 216
    Top = 104
  end
  object SaveDialog1: TSaveDialog
    DefaultExt = 'EXE'
    Filter = 'Executable files (*.exe)|*.exe'
    Options = [ofOverwritePrompt, ofHideReadOnly, ofPathMustExist, ofEnableSizing]
    Left = 248
    Top = 256
  end
end
